### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by PCAssistSoftware** [bsonnino/NtfsDirectories#1]
Firstly thank you so much for creating this project and the related article - much appreciated :)

Some suggestions below:-

1) Include the NtfsReader.dll in the GitHub download

2) Change

 ```
var ntfsDrives = DriveInfo.GetDrives()
                .Where(d => d.DriveFormat == "NTFS").ToList();
```

to

```
var ntfsDrives = DriveInfo.GetDrives()
                .Where(d =>  d.IsReady == true && d.DriveFormat == "NTFS").ToList();
```

So it handles computers (like mine) which have a card reader slot which causes System.IO.IOException as code is seeing a drive which it can't access as it is not ready

3) Add an app.manifest file and set

 ` <requestedExecutionLevel  level="requireAdministrator" uiAccess="false" />`

As if user selects the C: drive then they will get "System.IO.IOException: 'Unable to open volume C:\. Make sure it exists and that you have Administrator privileges.'" error if not

**Comment by bsonnino** [comment]
Done.
